[workspace]
preview = ["pixi-build"]
channels = ["https://prefix.dev/sdl", "conda-forge"]
platforms = ["linux-64", "osx-64", "win-64", "osx-arm64"]

[package]
name = "sdl3_image"
version = "3.3.0"

[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*" }

[package.build.config]
extra-args = [
    "-DCMAKE_BUILD_TYPE=Release",
    "-DBUILD_SHARED_LIBS=ON", # Turn to OFF to only build a static library
    "-DSDLIMAGE_VENDORED=OFF",
]

[package.host-dependencies]
cmake = ">=3.18"
sdl3 = "==3.3.3"
